# Generated by Django 5.0.7 on 2024-07-28 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.PositiveIntegerField()),
                ('is_IBAN', models.BooleanField(default=False)),
                ('IBAN', models.CharField(blank=True, max_length=34, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('Deposit', 'deposit'), ('Withdraw', 'withdraw'), ('Transfer', 'transfer')], max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.account')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
