# Generated by Django 5.0.7 on 2024-07-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='IBAN',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
