# Generated by Django 5.1 on 2024-08-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_alter_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_IBAN',
        ),
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
