# Generated by Django 5.1 on 2024-08-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_remove_account_is_iban_alter_movement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='IBAN',
            field=models.CharField(max_length=34, unique=True),
        ),
    ]
