# Generated by Django 5.0.7 on 2024-07-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_alter_account_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountstatement',
            options={'ordering': ['date']},
        ),
    ]
