# Generated by Django 5.0.7 on 2024-07-28 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_alter_accountstatement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('Deposit', 'deposit'), ('Withdraw', 'withdraw'), ('Transfer', 'transfer')], max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.account')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='AccountStatement',
        ),
    ]
